--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-24 11:34:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 242 (class 1259 OID 26700)
-- Name: Comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Comment" (
    comment_id integer NOT NULL,
    comment_content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public."Comment" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 26699)
-- Name: Comment_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Comment" ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comment_comment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 26714)
-- Name: Follow; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Follow" (
    id bigint NOT NULL,
    followed_at timestamp with time zone NOT NULL,
    followee_id integer NOT NULL,
    follower_id integer NOT NULL
);


ALTER TABLE public."Follow" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 26713)
-- Name: Follow_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Follow" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Follow_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 26648)
-- Name: Hashtag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hashtag" (
    hashtag_id integer NOT NULL,
    hashtag_name character varying(255) NOT NULL
);


ALTER TABLE public."Hashtag" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 26647)
-- Name: Hashtag_hashtag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hashtag" ALTER COLUMN hashtag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hashtag_hashtag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 26720)
-- Name: Like; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Like" (
    like_id integer NOT NULL,
    user_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public."Like" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 26719)
-- Name: Like_like_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Like" ALTER COLUMN like_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Like_like_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 26692)
-- Name: Media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Media" (
    media_id integer NOT NULL,
    media_type character varying(50) NOT NULL,
    media_content bytea,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public."Media" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 26691)
-- Name: Media_media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Media" ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Media_media_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 26684)
-- Name: Post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Post" (
    post_id integer NOT NULL,
    post_content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public."Post" OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 26726)
-- Name: Post_Hashtag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Post_Hashtag" (
    id bigint NOT NULL,
    hashtag_id integer NOT NULL,
    post_id integer NOT NULL
);


ALTER TABLE public."Post_Hashtag" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 26725)
-- Name: Post_Hashtag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Post_Hashtag" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Post_Hashtag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 26683)
-- Name: Post_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Post" ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Post_post_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 26656)
-- Name: Role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Role" (
    role_id integer NOT NULL,
    role_name character varying(255) NOT NULL
);


ALTER TABLE public."Role" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 26655)
-- Name: Role_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Role" ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Role_role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 26708)
-- Name: Session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Session" (
    session_id integer NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public."Session" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 26707)
-- Name: Session_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Session" ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Session_session_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 26662)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    user_id integer NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    profile_picture character varying(100),
    bio text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 26672)
-- Name: User_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User_groups" (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public."User_groups" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 26671)
-- Name: User_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User_groups" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 26661)
-- Name: User_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 26678)
-- Name: User_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User_user_permissions" (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public."User_user_permissions" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 26677)
-- Name: User_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User_user_permissions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 26861)
-- Name: admin_interface_theme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_interface_theme (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    active boolean NOT NULL,
    title character varying(50) NOT NULL,
    title_visible boolean NOT NULL,
    logo character varying(100) NOT NULL,
    logo_visible boolean NOT NULL,
    css_header_background_color character varying(10) NOT NULL,
    title_color character varying(10) NOT NULL,
    css_header_text_color character varying(10) NOT NULL,
    css_header_link_color character varying(10) NOT NULL,
    css_header_link_hover_color character varying(10) NOT NULL,
    css_module_background_color character varying(10) NOT NULL,
    css_module_text_color character varying(10) NOT NULL,
    css_module_link_color character varying(10) NOT NULL,
    css_module_link_hover_color character varying(10) NOT NULL,
    css_module_rounded_corners boolean NOT NULL,
    css_generic_link_color character varying(10) NOT NULL,
    css_generic_link_hover_color character varying(10) NOT NULL,
    css_save_button_background_color character varying(10) NOT NULL,
    css_save_button_background_hover_color character varying(10) NOT NULL,
    css_save_button_text_color character varying(10) NOT NULL,
    css_delete_button_background_color character varying(10) NOT NULL,
    css_delete_button_background_hover_color character varying(10) NOT NULL,
    css_delete_button_text_color character varying(10) NOT NULL,
    list_filter_dropdown boolean NOT NULL,
    related_modal_active boolean NOT NULL,
    related_modal_background_color character varying(10) NOT NULL,
    related_modal_rounded_corners boolean NOT NULL,
    logo_color character varying(10) NOT NULL,
    recent_actions_visible boolean NOT NULL,
    favicon character varying(100) NOT NULL,
    related_modal_background_opacity character varying(5) NOT NULL,
    env_name character varying(50) NOT NULL,
    env_visible_in_header boolean NOT NULL,
    env_color character varying(10) NOT NULL,
    env_visible_in_favicon boolean NOT NULL,
    related_modal_close_button_visible boolean NOT NULL,
    language_chooser_active boolean NOT NULL,
    language_chooser_display character varying(10) NOT NULL,
    list_filter_sticky boolean NOT NULL,
    form_pagination_sticky boolean NOT NULL,
    form_submit_sticky boolean NOT NULL,
    css_module_background_selected_color character varying(10) NOT NULL,
    css_module_link_selected_color character varying(10) NOT NULL,
    logo_max_height smallint NOT NULL,
    logo_max_width smallint NOT NULL,
    foldable_apps boolean NOT NULL,
    language_chooser_control character varying(20) NOT NULL,
    list_filter_highlight boolean NOT NULL,
    list_filter_removal_links boolean NOT NULL,
    show_fieldsets_as_tabs boolean NOT NULL,
    show_inlines_as_tabs boolean NOT NULL,
    css_generic_link_active_color character varying(10) NOT NULL,
    collapsible_stacked_inlines boolean NOT NULL,
    collapsible_stacked_inlines_collapsed boolean NOT NULL,
    collapsible_tabular_inlines boolean NOT NULL,
    collapsible_tabular_inlines_collapsed boolean NOT NULL,
    CONSTRAINT admin_interface_theme_logo_max_height_check CHECK ((logo_max_height >= 0)),
    CONSTRAINT admin_interface_theme_logo_max_width_check CHECK ((logo_max_width >= 0))
);


ALTER TABLE public.admin_interface_theme OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 26860)
-- Name: admin_interface_theme_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_interface_theme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_interface_theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 26608)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 26607)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 26616)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 26615)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 26602)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 26601)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 27056)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 27055)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 26594)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 26593)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 26575)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 26574)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 26906)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 26916)
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 26915)
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 26922)
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 26921)
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5143 (class 0 OID 26700)
-- Dependencies: 242
-- Data for Name: Comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Comment" (comment_id, comment_content, created_at, updated_at, user_id, post_id) FROM stdin;



--
-- TOC entry 5147 (class 0 OID 26714)
-- Dependencies: 246
-- Data for Name: Follow; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Follow" (id, followed_at, followee_id, follower_id) FROM stdin;



--
-- TOC entry 5129 (class 0 OID 26648)
-- Dependencies: 228
-- Data for Name: Hashtag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Hashtag" (hashtag_id, hashtag_name) FROM stdin;



--
-- TOC entry 5149 (class 0 OID 26720)
-- Dependencies: 248
-- Data for Name: Like; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Like" (like_id, user_id, post_id) FROM stdin;



--
-- TOC entry 5141 (class 0 OID 26692)
-- Dependencies: 240
-- Data for Name: Media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Media" (media_id, media_type, media_content, created_at, updated_at, post_id) FROM stdin;



--
-- TOC entry 5139 (class 0 OID 26684)
-- Dependencies: 238
-- Data for Name: Post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Post" (post_id, post_content, created_at, updated_at, user_id) FROM stdin;




--
-- TOC entry 5151 (class 0 OID 26726)
-- Dependencies: 250
-- Data for Name: Post_Hashtag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Post_Hashtag" (id, hashtag_id, post_id) FROM stdin;



--
-- TOC entry 5131 (class 0 OID 26656)
-- Dependencies: 230
-- Data for Name: Role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Role" (role_id, role_name) FROM stdin;



--
-- TOC entry 5145 (class 0 OID 26708)
-- Dependencies: 244
-- Data for Name: Session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Session" (session_id, token, created_at, expires_at, user_id) FROM stdin;



--
-- TOC entry 5133 (class 0 OID 26662)
-- Dependencies: 232
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" (last_login, is_superuser, user_id, username, email, password, profile_picture, bio, created_at, is_active, date_joined, updated_at, role_id) FROM stdin;




--
-- TOC entry 5135 (class 0 OID 26672)
-- Dependencies: 234
-- Data for Name: User_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User_groups" (id, user_id, group_id) FROM stdin;



--
-- TOC entry 5137 (class 0 OID 26678)
-- Dependencies: 236
-- Data for Name: User_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User_user_permissions" (id, user_id, permission_id) FROM stdin;



--
-- TOC entry 5153 (class 0 OID 26861)
-- Dependencies: 252
-- Data for Name: admin_interface_theme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_interface_theme (id, name, active, title, title_visible, logo, logo_visible, css_header_background_color, title_color, css_header_text_color, css_header_link_color, css_header_link_hover_color, css_module_background_color, css_module_text_color, css_module_link_color, css_module_link_hover_color, css_module_rounded_corners, css_generic_link_color, css_generic_link_hover_color, css_save_button_background_color, css_save_button_background_hover_color, css_save_button_text_color, css_delete_button_background_color, css_delete_button_background_hover_color, css_delete_button_text_color, list_filter_dropdown, related_modal_active, related_modal_background_color, related_modal_rounded_corners, logo_color, recent_actions_visible, favicon, related_modal_background_opacity, env_name, env_visible_in_header, env_color, env_visible_in_favicon, related_modal_close_button_visible, language_chooser_active, language_chooser_display, list_filter_sticky, form_pagination_sticky, form_submit_sticky, css_module_background_selected_color, css_module_link_selected_color, logo_max_height, logo_max_width, foldable_apps, language_chooser_control, list_filter_highlight, list_filter_removal_links, show_fieldsets_as_tabs, show_inlines_as_tabs, css_generic_link_active_color, collapsible_stacked_inlines, collapsible_stacked_inlines_collapsed, collapsible_tabular_inlines, collapsible_tabular_inlines_collapsed) FROM stdin;



--
-- TOC entry 5125 (class 0 OID 26608)
-- Dependencies: 224
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;



--
-- TOC entry 5127 (class 0 OID 26616)
-- Dependencies: 226
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;



--
-- TOC entry 5123 (class 0 OID 26602)
-- Dependencies: 222
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;



--
-- TOC entry 5154 (class 0 OID 26906)
-- Dependencies: 253
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;



--
-- TOC entry 5156 (class 0 OID 26916)
-- Dependencies: 255
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;



--
-- TOC entry 5158 (class 0 OID 26922)
-- Dependencies: 257
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;



--
-- TOC entry 5166 (class 0 OID 0)
-- Dependencies: 241
-- Name: Comment_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Comment_comment_id_seq"', 1, false);


--
-- TOC entry 5167 (class 0 OID 0)
-- Dependencies: 245
-- Name: Follow_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Follow_id_seq"', 1, false);


--
-- TOC entry 5168 (class 0 OID 0)
-- Dependencies: 227
-- Name: Hashtag_hashtag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Hashtag_hashtag_id_seq"', 1, false);


--
-- TOC entry 5169 (class 0 OID 0)
-- Dependencies: 247
-- Name: Like_like_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Like_like_id_seq"', 1, false);


--
-- TOC entry 5170 (class 0 OID 0)
-- Dependencies: 239
-- Name: Media_media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Media_media_id_seq"', 1, false);


--
-- TOC entry 5171 (class 0 OID 0)
-- Dependencies: 249
-- Name: Post_Hashtag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Post_Hashtag_id_seq"', 1, false);


--
-- TOC entry 5172 (class 0 OID 0)
-- Dependencies: 237
-- Name: Post_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Post_post_id_seq"', 1000, true);


--
-- TOC entry 5173 (class 0 OID 0)
-- Dependencies: 229
-- Name: Role_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Role_role_id_seq"', 1, true);


--
-- TOC entry 5174 (class 0 OID 0)
-- Dependencies: 243
-- Name: Session_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Session_session_id_seq"', 1, true);


--
-- TOC entry 5175 (class 0 OID 0)
-- Dependencies: 233
-- Name: User_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_groups_id_seq"', 1, false);


--
-- TOC entry 5176 (class 0 OID 0)
-- Dependencies: 231
-- Name: User_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_user_id_seq"', 101, true);


--
-- TOC entry 5177 (class 0 OID 0)
-- Dependencies: 235
-- Name: User_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_user_permissions_id_seq"', 1, false);


--
-- TOC entry 5178 (class 0 OID 0)
-- Dependencies: 251
-- Name: admin_interface_theme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_interface_theme_id_seq', 1, false);


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- TOC entry 5182 (class 0 OID 0)
-- Dependencies: 258
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5183 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- TOC entry 5184 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 70, true);


--
-- TOC entry 5185 (class 0 OID 0)
-- Dependencies: 254
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, true);


--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 256
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 1, true);


--
-- TOC entry 4903 (class 2606 OID 26706)
-- Name: Comment Comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comment"
    ADD CONSTRAINT "Comment_pkey" PRIMARY KEY (comment_id);


--
-- TOC entry 4912 (class 2606 OID 26798)
-- Name: Follow Follow_follower_id_followee_id_c5425c15_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Follow"
    ADD CONSTRAINT "Follow_follower_id_followee_id_c5425c15_uniq" UNIQUE (follower_id, followee_id);


--
-- TOC entry 4914 (class 2606 OID 26718)
-- Name: Follow Follow_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Follow"
    ADD CONSTRAINT "Follow_pkey" PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 26654)
-- Name: Hashtag Hashtag_hashtag_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hashtag"
    ADD CONSTRAINT "Hashtag_hashtag_name_key" UNIQUE (hashtag_name);


--
-- TOC entry 4875 (class 2606 OID 26652)
-- Name: Hashtag Hashtag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hashtag"
    ADD CONSTRAINT "Hashtag_pkey" PRIMARY KEY (hashtag_id);


--
-- TOC entry 4916 (class 2606 OID 26724)
-- Name: Like Like_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT "Like_pkey" PRIMARY KEY (like_id);


--
-- TOC entry 4919 (class 2606 OID 26812)
-- Name: Like Like_post_id_user_id_5f5c1c8a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT "Like_post_id_user_id_5f5c1c8a_uniq" UNIQUE (post_id, user_id);


--
-- TOC entry 4900 (class 2606 OID 26698)
-- Name: Media Media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Media"
    ADD CONSTRAINT "Media_pkey" PRIMARY KEY (media_id);


--
-- TOC entry 4923 (class 2606 OID 26730)
-- Name: Post_Hashtag Post_Hashtag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post_Hashtag"
    ADD CONSTRAINT "Post_Hashtag_pkey" PRIMARY KEY (id);


--
-- TOC entry 4926 (class 2606 OID 26826)
-- Name: Post_Hashtag Post_Hashtag_post_id_hashtag_id_59c7bca5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post_Hashtag"
    ADD CONSTRAINT "Post_Hashtag_post_id_hashtag_id_59c7bca5_uniq" UNIQUE (post_id, hashtag_id);


--
-- TOC entry 4897 (class 2606 OID 26690)
-- Name: Post Post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post"
    ADD CONSTRAINT "Post_pkey" PRIMARY KEY (post_id);


--
-- TOC entry 4877 (class 2606 OID 26660)
-- Name: Role Role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Role"
    ADD CONSTRAINT "Role_pkey" PRIMARY KEY (role_id);


--
-- TOC entry 4907 (class 2606 OID 26712)
-- Name: Session Session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Session"
    ADD CONSTRAINT "Session_pkey" PRIMARY KEY (session_id);


--
-- TOC entry 4880 (class 2606 OID 26670)
-- Name: User User_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_email_key" UNIQUE (email);


--
-- TOC entry 4886 (class 2606 OID 26676)
-- Name: User_groups User_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_groups"
    ADD CONSTRAINT "User_groups_pkey" PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 26740)
-- Name: User_groups User_groups_user_id_group_id_d63e199e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_groups"
    ADD CONSTRAINT "User_groups_user_id_group_id_d63e199e_uniq" UNIQUE (user_id, group_id);


--
-- TOC entry 4882 (class 2606 OID 26668)
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (user_id);


--
-- TOC entry 4892 (class 2606 OID 26682)
-- Name: User_user_permissions User_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_user_permissions"
    ADD CONSTRAINT "User_user_permissions_pkey" PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 26754)
-- Name: User_user_permissions User_user_permissions_user_id_permission_id_af0f54ec_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_user_permissions"
    ADD CONSTRAINT "User_user_permissions_user_id_permission_id_af0f54ec_uniq" UNIQUE (user_id, permission_id);


--
-- TOC entry 4929 (class 2606 OID 26882)
-- Name: admin_interface_theme admin_interface_theme_name_30bda70f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_interface_theme
    ADD CONSTRAINT admin_interface_theme_name_30bda70f_uniq UNIQUE (name);


--
-- TOC entry 4931 (class 2606 OID 26867)
-- Name: admin_interface_theme admin_interface_theme_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_interface_theme
    ADD CONSTRAINT admin_interface_theme_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 26645)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4867 (class 2606 OID 26631)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4870 (class 2606 OID 26620)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 26612)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4857 (class 2606 OID 26622)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4859 (class 2606 OID 26606)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4948 (class 2606 OID 27063)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 26600)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4854 (class 2606 OID 26598)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 26581)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 26912)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4937 (class 2606 OID 26954)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 4939 (class 2606 OID 26975)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- TOC entry 4942 (class 2606 OID 26945)
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- TOC entry 4944 (class 2606 OID 26963)
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 1259 OID 26790)
-- Name: Comment_post_id_13b5862e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Comment_post_id_13b5862e" ON public."Comment" USING btree (post_id);


--
-- TOC entry 4905 (class 1259 OID 26789)
-- Name: Comment_user_id_1cbe86a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Comment_user_id_1cbe86a2" ON public."Comment" USING btree (user_id);


--
-- TOC entry 4909 (class 1259 OID 26809)
-- Name: Follow_followee_id_7b602640; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Follow_followee_id_7b602640" ON public."Follow" USING btree (followee_id);


--
-- TOC entry 4910 (class 1259 OID 26810)
-- Name: Follow_follower_id_98224dd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Follow_follower_id_98224dd2" ON public."Follow" USING btree (follower_id);


--
-- TOC entry 4871 (class 1259 OID 26731)
-- Name: Hashtag_hashtag_name_ef67a6af_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Hashtag_hashtag_name_ef67a6af_like" ON public."Hashtag" USING btree (hashtag_name varchar_pattern_ops);


--
-- TOC entry 4917 (class 1259 OID 26824)
-- Name: Like_post_id_38d478db; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Like_post_id_38d478db" ON public."Like" USING btree (post_id);


--
-- TOC entry 4920 (class 1259 OID 26823)
-- Name: Like_user_id_bc2d2d58; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Like_user_id_bc2d2d58" ON public."Like" USING btree (user_id);


--
-- TOC entry 4901 (class 1259 OID 26778)
-- Name: Media_post_id_78005098; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Media_post_id_78005098" ON public."Media" USING btree (post_id);


--
-- TOC entry 4921 (class 1259 OID 26837)
-- Name: Post_Hashtag_hashtag_id_10b6695a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Post_Hashtag_hashtag_id_10b6695a" ON public."Post_Hashtag" USING btree (hashtag_id);


--
-- TOC entry 4924 (class 1259 OID 26838)
-- Name: Post_Hashtag_post_id_e5db413f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Post_Hashtag_post_id_e5db413f" ON public."Post_Hashtag" USING btree (post_id);


--
-- TOC entry 4898 (class 1259 OID 26772)
-- Name: Post_user_id_1eab9b38; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Post_user_id_1eab9b38" ON public."Post" USING btree (user_id);


--
-- TOC entry 4908 (class 1259 OID 26796)
-- Name: Session_user_id_0c85df5d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Session_user_id_0c85df5d" ON public."Session" USING btree (user_id);


--
-- TOC entry 4878 (class 1259 OID 26737)
-- Name: User_email_667201b5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_email_667201b5_like" ON public."User" USING btree (email varchar_pattern_ops);


--
-- TOC entry 4884 (class 1259 OID 26752)
-- Name: User_groups_group_id_328392a3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_groups_group_id_328392a3" ON public."User_groups" USING btree (group_id);


--
-- TOC entry 4887 (class 1259 OID 26751)
-- Name: User_groups_user_id_8f675f72; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_groups_user_id_8f675f72" ON public."User_groups" USING btree (user_id);


--
-- TOC entry 4883 (class 1259 OID 26738)
-- Name: User_role_id_0ae7280f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_role_id_0ae7280f" ON public."User" USING btree (role_id);


--
-- TOC entry 4890 (class 1259 OID 26766)
-- Name: User_user_permissions_permission_id_8e998ba4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_user_permissions_permission_id_8e998ba4" ON public."User_user_permissions" USING btree (permission_id);


--
-- TOC entry 4893 (class 1259 OID 26765)
-- Name: User_user_permissions_user_id_2c6da4d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "User_user_permissions_user_id_2c6da4d4" ON public."User_user_permissions" USING btree (user_id);


--
-- TOC entry 4927 (class 1259 OID 26883)
-- Name: admin_interface_theme_name_30bda70f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX admin_interface_theme_name_30bda70f_like ON public.admin_interface_theme USING btree (name varchar_pattern_ops);


--
-- TOC entry 4860 (class 1259 OID 26646)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4865 (class 1259 OID 26642)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4868 (class 1259 OID 26643)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4855 (class 1259 OID 26628)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4946 (class 1259 OID 27074)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4949 (class 1259 OID 27075)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4932 (class 1259 OID 26914)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4935 (class 1259 OID 26913)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4940 (class 1259 OID 26946)
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- TOC entry 4945 (class 1259 OID 26943)
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- TOC entry 4960 (class 2606 OID 26784)
-- Name: Comment Comment_post_id_13b5862e_fk_Post_post_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comment"
    ADD CONSTRAINT "Comment_post_id_13b5862e_fk_Post_post_id" FOREIGN KEY (post_id) REFERENCES public."Post"(post_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4961 (class 2606 OID 26779)
-- Name: Comment Comment_user_id_1cbe86a2_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comment"
    ADD CONSTRAINT "Comment_user_id_1cbe86a2_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4963 (class 2606 OID 26799)
-- Name: Follow Follow_followee_id_7b602640_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Follow"
    ADD CONSTRAINT "Follow_followee_id_7b602640_fk_User_user_id" FOREIGN KEY (followee_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4964 (class 2606 OID 26804)
-- Name: Follow Follow_follower_id_98224dd2_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Follow"
    ADD CONSTRAINT "Follow_follower_id_98224dd2_fk_User_user_id" FOREIGN KEY (follower_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4965 (class 2606 OID 26818)
-- Name: Like Like_post_id_38d478db_fk_Post_post_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT "Like_post_id_38d478db_fk_Post_post_id" FOREIGN KEY (post_id) REFERENCES public."Post"(post_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4966 (class 2606 OID 26813)
-- Name: Like Like_user_id_bc2d2d58_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT "Like_user_id_bc2d2d58_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4959 (class 2606 OID 26773)
-- Name: Media Media_post_id_78005098_fk_Post_post_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Media"
    ADD CONSTRAINT "Media_post_id_78005098_fk_Post_post_id" FOREIGN KEY (post_id) REFERENCES public."Post"(post_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4967 (class 2606 OID 26827)
-- Name: Post_Hashtag Post_Hashtag_hashtag_id_10b6695a_fk_Hashtag_hashtag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post_Hashtag"
    ADD CONSTRAINT "Post_Hashtag_hashtag_id_10b6695a_fk_Hashtag_hashtag_id" FOREIGN KEY (hashtag_id) REFERENCES public."Hashtag"(hashtag_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4968 (class 2606 OID 26832)
-- Name: Post_Hashtag Post_Hashtag_post_id_e5db413f_fk_Post_post_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post_Hashtag"
    ADD CONSTRAINT "Post_Hashtag_post_id_e5db413f_fk_Post_post_id" FOREIGN KEY (post_id) REFERENCES public."Post"(post_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4958 (class 2606 OID 26767)
-- Name: Post Post_user_id_1eab9b38_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Post"
    ADD CONSTRAINT "Post_user_id_1eab9b38_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4962 (class 2606 OID 26791)
-- Name: Session Session_user_id_0c85df5d_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Session"
    ADD CONSTRAINT "Session_user_id_0c85df5d_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4954 (class 2606 OID 26746)
-- Name: User_groups User_groups_group_id_328392a3_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_groups"
    ADD CONSTRAINT "User_groups_group_id_328392a3_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4955 (class 2606 OID 26741)
-- Name: User_groups User_groups_user_id_8f675f72_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_groups"
    ADD CONSTRAINT "User_groups_user_id_8f675f72_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4953 (class 2606 OID 26732)
-- Name: User User_role_id_0ae7280f_fk_Role_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_role_id_0ae7280f_fk_Role_role_id" FOREIGN KEY (role_id) REFERENCES public."Role"(role_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4956 (class 2606 OID 26760)
-- Name: User_user_permissions User_user_permission_permission_id_8e998ba4_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_user_permissions"
    ADD CONSTRAINT "User_user_permission_permission_id_8e998ba4_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4957 (class 2606 OID 26755)
-- Name: User_user_permissions User_user_permissions_user_id_2c6da4d4_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User_user_permissions"
    ADD CONSTRAINT "User_user_permissions_user_id_2c6da4d4_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4951 (class 2606 OID 26637)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4952 (class 2606 OID 26632)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4950 (class 2606 OID 26623)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4971 (class 2606 OID 27064)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4972 (class 2606 OID 27069)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_User_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_User_user_id" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4969 (class 2606 OID 26981)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4970 (class 2606 OID 26947)
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_User_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_User_user" FOREIGN KEY (user_id) REFERENCES public."User"(user_id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-04-24 11:34:57

--
-- PostgreSQL database dump complete
--

