# Generated by Django 5.2 on 2025-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
