# Generated by Django 5.2 on 2025-04-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
