# Generated by Django 5.2 on 2025-04-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("profile_picture", models.BinaryField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
