# Generated by Django 5.2 on 2025-04-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
