# Generated by Django 5.2 on 2025-04-21 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sessions_service", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
