# Generated by Django 5.2 on 2025-04-21 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
